FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG PUBLIC_AZURE_CLIENT_ID
ARG PUBLIC_AZURE_TENANT_ID
ARG PUBLIC_DASHBOARD_URL
ARG PUBLIC_EHEALTH_PORTAL_URL
ARG PUBLIC_OPENNCP_PORTAL_URL

ENV PUBLIC_AZURE_CLIENT_ID=$PUBLIC_AZURE_CLIENT_ID \
    PUBLIC_AZURE_TENANT_ID=$PUBLIC_AZURE_TENANT_ID \
    PUBLIC_DASHBOARD_URL=$PUBLIC_DASHBOARD_URL \
    PUBLIC_EHEALTH_PORTAL_URL=$PUBLIC_EHEALTH_PORTAL_URL \
    PUBLIC_OPENNCP_PORTAL_URL=$PUBLIC_OPENNCP_PORTAL_URL

RUN npm run build

FROM nginx:1.27-alpine AS runtime

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]